### ISSUE TITLE
For counter with n registers, it is possible to set the n+1'th register

### ISSUE THREAD

**Issue by skipperkongen** [ascv/HyperLogLog#13]
In line 240 of hll.c, there is a check that index is within size.

```c
if (index > self->size) {
    char * msg = "Index greater than the number of registers.";
    PyErr_SetString(PyExc_IndexError, msg);
    return NULL;
}
```

Should that not be `index >= self->size` ?

**Comment by ascv** [comment]
No, indexing is zero based.

**Comment by skipperkongen** [comment]
Well yes, exactly because it is zero based... :-)

for example, say size is 16. That means I'm allowed to set indices 0, 1, 2, 3, 4, ... 16, which is 17 indices total.

**Comment by ascv** [comment]
You are right. I misread the issue title as, "is it possible ..." instead of "it is possible" :)

**Comment by ascv** [comment]
If your size is 16, then the last register is at index 15 so it should be:

    index >= self->size - 1

**Comment by skipperkongen** [comment]
Seems there is another off-by-one in line https://github.com/ascv/HyperLogLog/blob/master/hll.c#L83

Why do you add +1 ?

**Comment by ascv** [comment]
B/c size = 2^k so if k=3 then size=2^3=8 so the last register index will be 7.

**Comment by skipperkongen** [comment]
Wait, the line I'm refering to is the one that computes the rank, not the index :-)

**Comment by skipperkongen** [comment]
For example, if the bitstring is 1111 0011 (k=4, using an 8 bit hash for clarity).
shifting left by 4 gives 0011 0000
shifting right by 4 gives 0000 0011
leading zeroes gives 6
subtracting k=4 gives 2
adding +1 gives 3

Should be 2, no?

**Comment by ascv** [comment]
rank(111) = 1 not 0, rank(01..) = 2 not 1. This is according to the reference paper:

    p(0^k) = k + 1

see page 140.

**Comment by skipperkongen** [comment]
Yep, you are right :-)

**Comment by ascv** [comment]
I think the intent is so that you can never get a rank of zero. A rank of zero would effectively contribute no information since the registers are initialized to zero.

**Comment by skipperkongen** [comment]
Good point!

**Comment by ascv** [comment]
This should be fixed now. Thanks for reporting and testing this issue.
