### ISSUE TITLE
string repr of the hll

### ISSUE THREAD

**Issue by DeoLeung** [ascv/HyperLogLog#23]
HI,

I wanna store the `hll` result into db, is there a way to get concise integer or string form of the hll instance?

thanks

**Comment by DeoLeung** [comment]
found it in the code https://github.com/ascv/HyperLogLog/blob/master/hll.c#L208

just use `pickle.dumps`

**Comment by ascv** [comment]
You can get a string representation using registers() which will return a bytearray of the registers:

```python
import binascii
from HLL import HyperLogLog

h = HyperLogLog(4)
h.add('some data')

print(h.registers())
print(map(int, h.registers()))
print(binascii.hexlify(h.registers()))
```
