### ISSUE TITLE
Incorrect cardinality after merge

### ISSUE THREAD

**Issue by JanFan** [ascv/HyperLogLog#25]
```python
hll1 = HyperLogLog(16)
hll2 = HyperLogLog(16)
for i in range(100000):
    hll1.add(str(random.random()))
for i in range(100000):
    hll2.add(str(random.random()))
for i in range(100000):
    r = str(random.random())
    hll1.add(r)
    hll2.add(r)

print(hll1.cardinality())
print(hll2.cardinality())

hll1.merge(hll2)
print(hll1.cardinality())
```
gives
```
201675.90068912748
201259.4273446178
201675.90068912748
```

the last one should be ~300k.

**Comment by ascv** [comment]
It looks hll1 is using the pre-merge cached cardinality. I put a fix on the v1.2.3 branch. I will get it pushed out later this weekend.

Nice catch.

**Comment by JanFan** [comment]
Do I have any workarounds before the fix?

**Comment by ascv** [comment]
Fix is live and should be available through pip. Let me know if you have any issues. Happy holidays!

**Comment by ascv** [comment]
I am still getting the issue on a machine I installed the package through pip. I am looking into it.

**Comment by ascv** [comment]
This turned out to be an issue local to my machine.
