### ISSUE TITLE
Inaccuracy percentage

### ISSUE THREAD

**Issue by sanjok-bless** [ascv/HyperLogLog#28]
I want to check is values an index (e.g. 1, 2, 3, ...) and I need to know inaccuracy percent. According HLL specification, accept counting error is calculated by the formula:

```
1.04 / math.sqrt(m),
    m - number of registers (2^k),
```
I set k to 12 and m=2^12=4096

```python
import math
inaccuracy_percent = 100 * (1.04 / math.sqrt(2**12))  # 1.625%
```
But in practice, the percentage is somewhere 2 times greater. For example, I have an 1M index values (potentially 50M). I add them to the algorithm for 100,000 values with the follow-up merge:
```python
from HLL import HyperLogLog

values = [range((0+i)*100000, (1+i)*100000) for i in xrange(10)]
rows_counter = 0
result = None
for chunk_values in values:
    rows_counter += len(chunk_values)
    hll = HyperLogLog(12)  # k=12
    [hll.add(str(x)) for x in chunk_values]
    if result:
        hll.merge(result)
    inaccuracy_percent = abs(1 - hll.cardinality() / rows_counter) * 100
    print(rows_counter, float('%.2f' % inaccuracy_percent), 0 <= inaccuracy_percent <= 1.625)
    result = hll
    if 0 <= inaccuracy_percent <= 1.625:
        # Values looks like index
        pass
    else:
        # Values is not index
        pass
```

Output:
```
(100000, 1.44, True)
(200000, 0.57, True)
(300000, 2.36, False)
(400000, 0.99, True)
(500000, 1.57, True)
(600000, 2.41, False)
(700000, 1.13, True)
(800000, 3.02, False)
(900000, 2.32, False)
(1000000, 2.55, False)
```
Why percentage is somewhere 2 times greater than 1.625? Or how can I calculate exact inaccuracy percentage?

**Comment by ascv** [comment]
> According HLL specification, accept counting error is calculated by the formula:
>
>     1.04 / math.sqrt(m),
>        m - number of registers (2^k),
> [...] Why percentage is somewhere 2 times greater than 1.625?

That formula computes the [standard error](https://en.wikipedia.org/wiki/Standard_error) but your code is computing the [percent error](https://en.wikipedia.org/wiki/Approximation_error).  They're not the same thing. See Theorem 1 in [[1](http://algo.inria.fr/flajolet/Publications/FlFuGaMe07.pdf)] for standard error derivation. 

> Or how can I calculate exact inaccuracy percentage?

What you are doing is fine. Using the relative error or percent error is the common way to measure the accuracy.

**Comment by sanjok-bless** [comment]
Thanks for the quick response.

I do not necessarily need a percentage error, I just went this way, the wrong way. I need to understand when the values go beyond the permissible error. Ie it all comes down to calculating standard error in the data stream. I look in the documentation [[1](http://algo.inria.fr/flajolet/Publications/FlFuGaMe07.pdf)] and I think how to implement it ...

**Comment by sanjok-bless** [comment]
I stopped counting the percentage and now counting the standard error:
```python
standard_error = 1.04 / math.sqrt(2**12)  # 0.01625
```
By the link above [standard error](https://en.wikipedia.org/wiki/Standard_error), in particular the picture 
![standard_deviation_diagram](https://user-images.githubusercontent.com/13743726/42521648-0a45ad54-8472-11e8-8ff6-46abf4d6d0cc.png)
shows that the distribution of the standard error will be as follows:
```
68.2% - 1*standard_error # standard_error <= 0.01625
27.2% - 2*standard_error # 0.01625 < standard_error <= 0.0325
 4.2% - 3*standard_error # 0.0325 < standard_error <= 0.04875
```
In my example, the probabilities are:
```
('1*standard_error', 0.5)
('2*standard_error', 0.5)
('3*standard_error', 0.0)
```
They are not accurate due to the small number of samples (10 out of a 1M), but now it is clear why the error was more than 0.01625. I can manage inaccuracies with such probabilities:
```
68.2% - 1*standard_error # standard_error <= 0.01625
95.4% - 2*standard_error # standard_error <= 0.0325
99.6% - 3*standard_error # standard_error <= 0.04875
```
