### ISSUE TITLE
`merge()` is broken in 2.0.1

### ISSUE THREAD

**Issue by ascv** [ascv/HyperLogLog#40]
The method hasn't been updated to handle sparse vs dense representations.

**Comment by kuk** [comment]
Let's say `c = merge(a, b)`
if `a` or `b` is dense `c` also dense
if `a` and `b` are sparse `c` is space

Right? That is what need to be implemented?

**Comment by ascv** [comment]
@kuk Yes, merging registers in sparse representation needs to be implemented. This would include merging HyperLogLogs using different representations (e.g. `merge(A, B)` where `A` is sparse and `B` is dense).
